apiVersion: apps/v1
kind: Deployment
metadata:
  name: bb-api
  labels:
    app: boerenboodschap
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boerenboodschap
  template:
    metadata:
      labels:
        app: boerenboodschap
    spec:
      containers:
        - name: bb-api
          image: tuin/bb-api:latest
          ports:
            - containerPort: 80
