---
name: CI-CD
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  directus:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18.17
      - name: npm install
        run: cd ./directus-node && npm install
      - name: run the database
        run: cd ./directus-docker && docker compose up -d
      - name: Directus Bootstrap
        run: cd ./directus-node && npx directus bootstrap
      - name: Apply Schema
        run: npx directus schema apply --yes ./snapshot.yaml
      - name: Start Directus
        run: cd ./directus-node && npx directus start
