---
name: CI-CD
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  directus:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
          node-version: 18.17
          # Set this option if you want the action to check for the latest available version that satisfies the version spec.
          # check-latest: true
          # Used to specify a package manager for caching in the default directory. Supported values: npm, yarn, pnpm.
          # cache: # optional
      - name: cd to directus-node
        run: cd ./directus-node
      - name: ls
        run: ls
      - name: pwd
        run: pwd
      - name: npm install
        run: cd ./directus-node && npm install
      - name: Directus Bootstrap
        run: cd ./directus-node && npx directus bootstrap
      - name: Apply Schema
        run: npx directus schema apply --yes ./snapshot.yaml
      - name: Start Directus
        run: cd ./directus-node && npx directus start
          
